### ISSUE TITLE
one failed test

### ISSUE THREAD

**Issue by hzahera** [dice-group/dice-embeddings#73] opened 2023-01-02 10:59 UTC
After installing Dice-embedding library in the Raki server. I got this error? 
```
(dice) zahera@raki:~$ pytest -p no:warnings -x # it takes circa 15 minutes
========================================================================================= test session starts =========================================================================================
platform linux -- Python 3.9.12, pytest-6.2.5, py-1.11.0, pluggy-1.0.0
rootdir: /local/upb/users/z/zahera/profiles/unix/cs
plugins: anyio-3.6.2
collected 79 items                                                                                                                                                                                    

dice-embeddings/tests/test_continual_training.py ..                                                                                                                                             [  2%]
dice-embeddings/tests/test_custom_trainer.py .......                                                                                                                                            [ 11%]
dice-embeddings/tests/test_deployment.py .                                                                                                                                                      [ 12%]
dice-embeddings/tests/test_different_backends.py .F

============================================================================================== FAILURES ===============================================================================================
________________________________________________________________________________ TestPolyak.test_modin_rdf_as_backend _________________________________________________________________________________

cls = <class 'modin.config.envvars.Engine'>

    @classmethod
    def get(cls) -> Any:
        """
        Get config value.
    
        Returns
        -------
        Any
            Decoded and verified config value.
        """
        if cls._value is _UNSET:
            # get the value from env
            try:
>               raw = cls._get_raw_from_config()

/upb/users/z/zahera/profiles/unix/cs/.conda/envs/dice/lib/python3.9/site-packages/modin/config/pubsub.py:260: 
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _

cls = <class 'modin.config.envvars.Engine'>

    @classmethod
    def _get_raw_from_config(cls) -> str:
        """
        Read the value from environment variable.
    
        Returns
        -------
        str
            Config raw value.
    
        Raises
        ------
        TypeError
            If `varname` is None.
        KeyError
            If value is absent.
        """
        if cls.varname is None:
            raise TypeError("varname should not be None")
>       return os.environ[cls.varname]

/upb/users/z/zahera/profiles/unix/cs/.conda/envs/dice/lib/python3.9/site-packages/modin/config/envvars.py:51: 
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _

self = environ({'SHELL': '/bin/bash', 'CONDA_EXE': '/opt/conda/bin/conda', '_CE_M': '', 'TMUX': '/tmp//tmux-66820/default,100...ce-embeddings/tests/test_different_backends.py::TestPolyak::test_modin_rdf_as_backend (call)', 'OMP_NUM_THREADS': '1'})
key = 'MODIN_ENGINE'

    def __getitem__(self, key):
        try:
            value = self._data[self.encodekey(key)]
        except KeyError:
            # raise KeyError with the original key value
>           raise KeyError(key) from None
E           KeyError: 'MODIN_ENGINE'

/upb/users/z/zahera/profiles/unix/cs/.conda/envs/dice/lib/python3.9/os.py:679: KeyError

During handling of the above exception, another exception occurred:

self = <tests.test_different_backends.TestPolyak object at 0x7f168d5de940>

    @pytest.mark.filterwarnings('ignore::UserWarning')
    def test_modin_rdf_as_backend(self):
        args = argparse_default([])
        args.path_dataset_folder = 'KGs/Family'
        args.backend = 'modin'
>       Execute(args).start()

dice-embeddings/tests/test_different_backends.py:34: 
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _
dice-embeddings/core/executer.py:104: in start
    self.load_indexed_data() if self.is_continual_training else self.read_preprocess_index_serialize_data()
dice-embeddings/core/executer.py:54: in read_preprocess_index_serialize_data
    self.dataset = read_or_load_kg(self.args, cls=KG)
dice-embeddings/core/static_funcs.py:268: in read_or_load_kg
    kg = cls(data_dir=args.path_dataset_folder,
dice-embeddings/core/knowledge_graph.py:45: in __init__
    ReadFromDisk(kg=self).start()
dice-embeddings/core/read_preprocess_save_load_kg/read_from_disk.py:25: in start
    self.kg.train_set = read_from_disk(i, self.kg.read_only_few, self.kg.sample_triples_ratio,
dice-embeddings/core/read_preprocess_save_load_kg/util.py:157: in read_from_disk
    return read_with_modin(data_path, read_only_few, sample_triples_ratio)
dice-embeddings/core/read_preprocess_save_load_kg/util.py:19: in timeit_wrapper
    result = func(*args, **kwargs)
dice-embeddings/core/read_preprocess_save_load_kg/util.py:47: in read_with_modin
    df = pd.read_csv(data_path,
/upb/users/z/zahera/profiles/unix/cs/.conda/envs/dice/lib/python3.9/site-packages/modin/logging/logger_decorator.py:128: in run_and_log
    return obj(*args, **kwargs)
/upb/users/z/zahera/profiles/unix/cs/.conda/envs/dice/lib/python3.9/site-packages/modin/_compat/pandas_api/latest/io.py:156: in read_csv
    return _read(**kwargs)
/upb/users/z/zahera/profiles/unix/cs/.conda/envs/dice/lib/python3.9/site-packages/modin/_compat/pandas_api/common/io.py:35: in _read
    Engine.subscribe(_update_engine)
/upb/users/z/zahera/profiles/unix/cs/.conda/envs/dice/lib/python3.9/site-packages/modin/config/pubsub.py:217: in subscribe
    callback(cls)
/upb/users/z/zahera/profiles/unix/cs/.conda/envs/dice/lib/python3.9/site-packages/modin/pandas/__init__.py:136: in _update_engine
    publisher.get() == "Native"
/upb/users/z/zahera/profiles/unix/cs/.conda/envs/dice/lib/python3.9/site-packages/modin/config/pubsub.py:262: in get
    cls._value = cls._get_default()
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _

cls = <class 'modin.config.envvars.Engine'>

    @classmethod
    def _get_default(cls) -> str:
        """
        Get default value of the config.
    
        Returns
        -------
        str
        """
        from modin.utils import (
            MIN_RAY_VERSION,
            MIN_DASK_VERSION,
        )
    
        if IsDebug.get():
            return "Python"
        try:
            import ray
    
        except ImportError:
            pass
        else:
            if version.parse(ray.__version__) < MIN_RAY_VERSION:
                raise ImportError(
                    "Please `pip install modin[ray]` to install compatible Ray "
                    + "version "
                    + f"(>={MIN_RAY_VERSION})."
                )
            return "Ray"
        try:
            import dask
            import distributed
    
        except ImportError:
            pass
        else:
            if (
                version.parse(dask.__version__) < MIN_DASK_VERSION
                or version.parse(distributed.__version__) < MIN_DASK_VERSION
            ):
                raise ImportError(
                    f"Please `pip install modin[dask]` to install compatible Dask version (>={MIN_DASK_VERSION})."
                )
            return "Dask"
        try:
            # We import ``DbWorker`` from this module since correct import of ``DbWorker`` itself
            # from HDK is located in it with all the necessary options for dlopen.
            from modin.experimental.core.execution.native.implementations.hdk_on_native.db_worker import (  # noqa
                DbWorker,
            )
        except ImportError:
            pass
        else:
            return "Native"
>       raise ImportError(
            "Please refer to installation documentation page to install an engine"
        )
E       ImportError: Please refer to installation documentation page to install an engine

/upb/users/z/zahera/profiles/unix/cs/.conda/envs/dice/lib/python3.9/site-packages/modin/config/envvars.py:134: ImportError
---------------------------------------------------------------------------------------- Captured stdout call -----------------------------------------------------------------------------------------
*** Read or Load Knowledge Graph  ***
*** Reading KGs/Family/train.txt with Modin ***
Reading with modin.read_csv with sep ** s+ ** ...
======================================================================================= short test summary info =======================================================================================
FAILED dice-embeddings/tests/test_different_backends.py::TestPolyak::test_modin_rdf_as_backend - ImportError: Please refer to installation documentation page to install an engine
!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!! stopping after 1 failures !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
=============================================================================== 1 failed, 11 passed in 64.42s (0:01:04) ===============================================================================
```

**Comment by Demirrr** [comment] 2023-01-02 12:55
Dear @hzahera ,

Thank you for giving a try :)  

The modin expects that either Ray or Dask has been already installed in the system.  I haven't specified the use of Ray or Dask in the readme as it depends on the user. I will update the readme accordingly. Please install one of the following library
```
pip3 install modin[ray]==0.16.2 
```
or
```
pip3 install modin[dask]==0.16.2 
```

**Comment by hzahera** [comment] 2023-02-16 16:44
I got another one test fail, when I cloned the code and test it :

```

Training is starting 2023-02-16 17:42:08.220374...
NumOfDataPoints:5216 | NumOfEpochs:256 | LearningRate:0.1 | BatchSize:256 | EpochBatchsize:21
======================================================== short test summary info ========================================================
FAILED tests/test_pickle.py::TestPickle::test_qmult_pickle - RuntimeError: torch.hsplit attempted to split along dimension 1, but the ...
!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!! stopping after 1 failures !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
=============================================== 1 failed, 54 passed in 462.20s (0:07:42) ================================================
```

**Comment by Demirrr** [comment] 2023-02-17 07:12
I am unable to reproduce this issue. Please share your more info about instalation steps and the branch used

**Comment by hzahera** [comment] 2023-02-17 14:12
I have installed the dice-embedding library from the develop branch with the following requirements

```
git clone https://github.com/dice-group/dice-embeddings.git
conda create -n dice python=3.9.12
conda activate dice
# Choose a backend
pip3 install pandas==1.5.1 
pip3 install polars==0.15.13 
pip3 install pyarrow==8.0.0
pip3 install torch==1.13.0 
pip3 install pytorch-lightning==1.6.4
pip3 install scikit-learn==1.1.1
pip3 install pytest==6.2.5
pip3 install gradio==3.0.17
```

During the test cases, I got the above-mentioned error.

**Comment by Demirrr** [comment] 2023-02-17 14:14
which branch ?

**Comment by hzahera** [comment] 2023-02-17 14:57
This library was installed, I am still getting the same error. Here I share the full output. Is there anything wrong in my installation :)? 
```

__________________________________________________________________ TestPickle.test_qmult_pickle __________________________________________________________________

self = <tests.test_pickle.TestPickle object at 0x7f8e5c600df0>

    @pytest.mark.filterwarnings('ignore::UserWarning')
    def test_qmult_pickle(self):
        args = argparse_default([])
        args.path_dataset_folder = 'KGs/UMLS'
        args.model = 'QMult'
        args.scoring_technique = 'NegSample'
        executor = Execute(args)
        args.trainer = 'torchCPUTrainer'
>       executor.start()

tests/test_pickle.py:44: 
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 
core/executer.py:129: in start
    self.trained_model, form_of_labelling = self.trainer.start(dataset=self.dataset)
core/trainer/dice_trainer.py:202: in start
    self.trainer.fit(model, train_dataloaders=train_loader)
core/trainer/torch_trainer.py:129: in fit
    avg_epoch_loss = self._run_epoch(epoch)
core/trainer/torch_trainer.py:83: in _run_epoch
    batch_loss = self._run_batch(i, x_batch, y_batch)
core/trainer/torch_trainer.py:61: in _run_batch
    return self.compute_forward_loss_backward(x_batch, y_batch).item()
core/trainer/torch_trainer.py:165: in compute_forward_loss_backward
    yhat_batch = self.model(x_batch)
../../../.conda/envs/dice/lib/python3.9/site-packages/torch/nn/modules/module.py:1190: in _call_impl
    return forward_call(*input, **kwargs)
core/models/base_model.py:235: in forward
    return self.forward_triples(x)
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 

self = QMult(
  (loss): BCEWithLogitsLoss()
  (normalize_head_entity_embeddings): IdentityClass()
  (normalize_relation_embed...): Dropout(p=0.0, inplace=False)
  (entity_embeddings): Embedding(135, 10)
  (relation_embeddings): Embedding(46, 10)
)
indexed_triple = tensor([[  2,   5, 114],
        [ 62,   0,  66],
        [ 47,   6,   4],
        [ 26,   4,  13],
        [ 39,   6,...  [ 76,  20,  32],
        [ 63,   5,  41],
        [ 80,   2, 125],
        [106,  16, 129],
        [ 84,  40,  62]])

    def forward_triples(self, indexed_triple: torch.Tensor) -> torch.Tensor:
        # (1) Retrieve embeddings & Apply Dropout & Normalization.
        head_ent_emb, rel_ent_emb, tail_ent_emb = self.get_triple_representation(indexed_triple)
        # (2) Split (1) into real and imaginary parts.
>       emb_head_real, emb_head_i, emb_head_j, emb_head_k = torch.hsplit(head_ent_emb, 4)
E       RuntimeError: torch.hsplit attempted to split along dimension 1, but the size of the dimension 10 is not divisible by the split_size 4!

core/models/quaternion.py:35: RuntimeError
---------------------------------------------------------------------- Captured stdout call ----------------------------------------------------------------------
Start time:2023-02-17 15:50:24.062274
*** Read or Load Knowledge Graph  ***
*** Reading KGs/UMLS/test.txt with Pandas ***
Reading with pandas.read_csv with sep ** s+ ** ...
Took 0.0060 seconds | Current Memory Usage  4189.3 in MB
*** Reading KGs/UMLS/valid.txt with Pandas ***
Reading with pandas.read_csv with sep ** s+ ** ...
Took 0.0023 seconds | Current Memory Usage  4189.3 in MB
*** Reading KGs/UMLS/train.txt with Pandas ***
Reading with pandas.read_csv with sep ** s+ ** ...
Took 0.0083 seconds | Current Memory Usage  4189.3 in MB

Concatenating data to obtain index...
Done !

Creating a mapping from entities to integer indexes...
Done !

Done ! 0.007 seconds

Done !

Done !

Took 0.0150 seconds | Current Memory Usage  4189.3 in MB
Data Type conversion...
Submit er-vocab, re-vocab, and ee-vocab via  ProcessPoolExecutor...
Preprocessing took: 0.204 seconds

------------------- Description of Dataset KGs/UMLS -------------------
Number of entities:135
Number of relations:46
Number of triples on train set:5216
Number of triples on valid set:652
Number of triples on test set:661
Entity Index:0.00000 in GB
Relation Index:0.00000 in GB
Train set :0.00003 in GB

# of CPUs:40 | # of GPUs:1 | # of CPUs for dataloader:0
NVIDIA GeForce RTX 3090
------------------- Train -------------------
Initializing TorchTrainer CPU Trainer...        Took 0.0006 seconds | Current Memory Usage  4187.3 in MB
Initializing Model...   Took 0.0021 seconds | Current Memory Usage  4187.3 in MB
Initializing Dataset... Took 0.0631 seconds | Current Memory Usage  4188.1 in MB
Took 0.0633 seconds | Current Memory Usage  4188.1 in MB
Took 0.0634 seconds | Current Memory Usage  4188.1 in MB
Initializing Dataloader...      Took 0.0005 seconds | Current Memory Usage  4188.1 in MB
QMult(
  (loss): BCEWithLogitsLoss()
  (normalize_head_entity_embeddings): IdentityClass()
  (normalize_relation_embeddings): IdentityClass()
  (normalize_tail_entity_embeddings): IdentityClass()
  (hidden_normalizer): IdentityClass()
  (input_dp_ent_real): Dropout(p=0.0, inplace=False)
  (input_dp_rel_real): Dropout(p=0.0, inplace=False)
  (hidden_dropout): Dropout(p=0.0, inplace=False)
  (entity_embeddings): Embedding(135, 10)
  (relation_embeddings): Embedding(46, 10)
)
  | Name                             | Type              | Params
-----------------------------------------------------------------------
0 | loss                             | BCEWithLogitsLoss | 0     
1 | normalize_head_entity_embeddings | IdentityClass     | 0     
2 | normalize_relation_embeddings    | IdentityClass     | 0     
3 | normalize_tail_entity_embeddings | IdentityClass     | 0     
4 | hidden_normalizer                | IdentityClass     | 0     
5 | input_dp_ent_real                | Dropout           | 0     
6 | input_dp_rel_real                | Dropout           | 0     
7 | hidden_dropout                   | Dropout           | 0     
8 | entity_embeddings                | Embedding         | 1.4 K 
9 | relation_embeddings              | Embedding         | 460   
-----------------------------------------------------------------------
1.8 K     Trainable params
0         Non-trainable params
1.8 K     Total params
0.007     Total estimated model params size (MB)
Adam (
Parameter Group 0
    amsgrad: False
    betas: (0.9, 0.999)
    capturable: False
    differentiable: False
    eps: 1e-08
    foreach: None
    fused: False
    lr: 0.1
    maximize: False
    weight_decay: 0.0
)

Training is starting 2023-02-17 15:50:24.341194...
NumOfDataPoints:5216 | NumOfEpochs:256 | LearningRate:0.1 | BatchSize:256 | EpochBatchsize:21
==================================================================== short test summary info =====================================================================
FAILED tests/test_pickle.py::TestPickle::test_qmult_pickle - RuntimeError: torch.hsplit attempted to split along dimension 1, but the size of the dimension 10 ...
!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!! stopping after 1 failures !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
============================================================ 1 failed, 54 passed in 452.90s (0:07:32) ============================================================
```

**Comment by Demirrr** [comment] 2023-02-17 16:06
As said before, I am unable to reproduce this error. 

Please rerun the below code and share the all output, if a test fails.
```
git clone https://github.com/dice-group/dice-embeddings.git
git checkout CLF 
conda create -n dice python=3.9.12
conda activate dice
pip3 install pandas==1.5.1 
pip3 install polars==0.15.13 
pip3 install modin[ray]==0.16.2 
pip3 install pyarrow==8.0.0
pip3 install torch==1.13.0 
pip3 install pytorch-lightning==1.6.4
pip3 install scikit-learn==1.1.1
pip3 install pytest==6.2.5
pip3 install gradio==3.0.17

wget https://hobbitdata.informatik.uni-leipzig.de/KG/KGs.zip
unzip KGs.zip
pytest -p no:warnings -x 
```

**Comment by hzahera** [comment] 2023-02-17 16:46
I got this error while installing `pip3 install pytorch-lightning==1.6.4`

```

->tensorboard>=2.2.0->pytorch-lightning==1.6.4) (0.4.8)
Collecting oauthlib>=3.0.0
  Using cached oauthlib-3.2.2-py3-none-any.whl (151 kB)
Installing collected packages: tensorboard-plugin-wit, zipp, tqdm, tensorboard-data-server, pyDeprecate, protobuf, oauthlib, MarkupSafe, absl-py, werkzeug, requests-oauthlib, importlib-metadata, markdown, google-auth-oauthlib, torchmetrics, tensorboard, pytorch-lightning
  Attempting uninstall: protobuf
    Found existing installation: protobuf 4.22.0
    Uninstalling protobuf-4.22.0:
      Successfully uninstalled protobuf-4.22.0
ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
googleapis-common-protos 1.58.0 requires protobuf!=3.20.0,!=3.20.1,!=4.21.1,!=4.21.2,!=4.21.3,!=4.21.4,!=4.21.5,<5.0.0dev,>=3.19.5, but you have protobuf 3.20.1 which is incompatible.
google-api-core 2.11.0 requires protobuf!=3.20.0,!=3.20.1,!=4.21.0,!=4.21.1,!=4.21.2,!=4.21.3,!=4.21.4,!=4.21.5,<5.0.0dev,>=3.19.5, but you have protobuf 3.20.1 which is incompatible.
Successfully installed MarkupSafe-2.1.2 absl-py-1.4.0 google-auth-oauthlib-0.4.6 importlib-metadata-6.0.0 markdown-3.4.1 oauthlib-3.2.2 protobuf-3.20.1 pyDeprecate-0.3.2 pytorch-lightning-1.6.4 requests-oauthlib-1.3.1 tensorboard-2.12.0 tensorboard-data-server-0.7.0 tensorboard-plugin-wit-1.8.1 torchmetrics-0.11.1 tqdm-4.64.1 werkzeug-2.2.3 zipp-3.13.0
```

**Comment by Demirrr** [comment] 2023-02-17 17:37
I am closing this issue as there is no single test is failed by executing the instructions shown here https://github.com/dice-group/dice-embeddings/issues/73#issuecomment-1434854264 as well as [in the readme](https://github.com/dice-group/dice-embeddings/tree/CLF#installation)

**Closed by Demirrr** 2023-02-17 17:37 UTC
